spring.application.name=employee-service
server.port=8082

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=${EMPLOYEE_DB_URL:jdbc:postgresql://localhost:5432/nexushr_employee}
spring.datasource.username=${EMPLOYEE_DB_USERNAME:postgres}
spring.datasource.password=${EMPLOYEE_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=${JWT_SECRET:7f4c4e657875734852446179325365637265744b6579466f724a77745369676e696e674b6579313233}
