spring.application.name=auth-service
server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5432/nexushr_auth}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${AUTH_DB_USERNAME:postgres}
spring.datasource.password=${AUTH_DB_PASSWORD:tiger}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2s

security.jwt.secret=7f4c4e657875734852446179325365637265744b6579466f724a77745369676e696e674b6579313233
security.jwt.access-token-expiration=900000
security.jwt.refresh-token-expiration=604800000

app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:5173}
