spring.application.name=payroll-service
server.port=8083

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=${PAYROLL_DB_URL:jdbc:postgresql://localhost:5432/nexushr_payroll}
spring.datasource.username=${PAYROLL_DB_USERNAME:postgres}
spring.datasource.password=${PAYROLL_DB_PASSWORD:tiger}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
